baseURL: https://liuhuisheng.com/
languageCode: UTF-8
title: Huisheng Liu
theme: hugo-theme-cactus
copyright: LHS
disqusShortname: LHS
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 5
    - name: Writings
      url: /posts
      weight: 2
    - name: Topics
      url: /tags
      weight: 3
    - name: Solitude
      url: /Solitude
      weight: 4

markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: classic
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: 今日はまるで昨日みたいだ　明日を変えるなら今日を変えなきゃ
  
  mathjax: yes
  
  googleAnalyticsAsync: yes
  mainSection: posts 
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: yes
  showAllPostsOnHomePage: yes
  showProjectsList: yes
  social:
    - link: https://github.com/Farewellznm
      name: github
    - link: huishengliu06@gmail.com
      name: email
  tagsOverview: no
  enableEmoji: True
  
  
  
