baseURL: https://liuhuisheng.com/
languageCode: en-us
title: 纵有疾风起，人生不言弃
theme: hugo-theme-cactus
copyright: You
disqusShortname: LHS
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: 没想到写什么介绍啊
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  social:
    - link: https://github.com/Farewellznm
      name: github
    - link: https://www.linkedin.com/company/github/
      name: linkedin
    - link: huishengliu06@gmail.com
      name: email
  tagsOverview: yes
