baseURL: https://liuhuisheng.com/
languageCode: UTF-8
title: Huisheng Liu
theme: hugo-theme-cactus
copyright: LHS
disqusShortname: LHS
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 5
    - name: Writings
      url: /posts
      weight: 2
    - name: Topics
      url: /tags
      weight: 3
    - name: Solitude
      url: /Solitude
      weight: 4

markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: light
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: 2021年6月我挣扎着从五山禅院大学城分校硕士毕业了；最爱的是广州的木棉花，最难忍受的是潮热和暴雨。然而因为一些原因，我来上海工作了，作为一个【新参者】我逐渐熟悉着这座城市，2021年对于我来说是充实的一年。
  mathjax: yes
  googleAnalyticsAsync: yes
  mainSection: posts 
  postsOnHomePage: 10
  projectsUrl: https://github.com/Farewellznm
  rss: yes
  show_updated: yes
  showAllPostsOnHomePage: no
  showProjectsList: yes
  social:
    - link: https://github.com/Farewellznm
      name: github
    - link: huishengliu06@gmail.com
      name: email
  tagsOverview: no
  enableEmoji: True
  
  
  
