baseURL: https://liuhuisheng.com/
languageCode: UTF-8
title: Huisheng Liu
theme: hugo-theme-cactus
copyright: LHS
disqusShortname: LHS
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 5
    - name: Writings
      url: /posts
      weight: 2
#    - name: Toolkits
#      url: /Toolkits
#      weight: 3
    - name: 中文
      url: /writes
      weight: 4


markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: light
  comments:
    enabled: yes
    engine: disqus
  dateFormat: '2006-01-02'
  description: Perhaps for a longer period of time, with periods of bitterness and long vacations，What should be done at these times?
  mathjax: yes
  googleAnalyticsAsync: yes
  mainSection: posts 
  postsOnHomePage: 4
  projectsUrl: https://github.com/Farewellznm
  rss: yes
  show_updated: yes
  showAllPostsOnHomePage: no
  showProjectsList: no
  social:
    - link: https://github.com/Farewellznm
      name: github
    - link: huishengliu06@gmail.com
      name: email
  tagsOverview: no
  enableEmoji: True
  
  
  
