baseURL: https://liuhuisheng.com/
languageCode: UTF-8
title: Huisheng Liu
theme: hugo-theme-cactus
copyright: LHS
disqusShortname: LHS
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Writings
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: Friendlinks
      url: /about
      weight: 4
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: classic
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: 2021年6月，我来上海啦！/t 这些地方走在众人之前，它们已经有了自己的花冠女神。/t 而我的花冠女神。 
  
  mathjax: yes
  
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: no
  showAllPostsOnHomePage: yes
  showProjectsList: no
  social:
    - link: https://github.com/Farewellznm
      name: github
    #- link: https://www.linkedin.com/company/github/
    #  name: linkedin
    - link: huishengliu06@gmail.com
      name: email
  tagsOverview: yes
  enableEmoji: True
  
  
  
