baseURL: https://liuhuisheng.com/
languageCode: UTF-8
title: Huisheng Liu
theme: hugo-theme-cactus
copyright: LHS
disqusShortname: LHS
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about
      weight: 5
    - name: Writings
      url: /posts
      weight: 2
    - name: Topics
      url: /tags
      weight: 3
    - name: Solitude
      url: /Solitude
      weight: 4

markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: classic
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: 方木，你好像躲在一个看上去透明，却又厚厚的壳子里，我可以帮你打碎
  它。其实没那么难，就像打碎一面镜子，你只需要盯着它，面对它。别这么傲娇，更别
  恐惧，也就是一挥拳，就算是手破了，又能流多少血呢？《心理罪》2017
  
  mathjax: yes
  
  googleAnalyticsAsync: yes
  mainSection: posts 
  postsOnHomePage: 5
  projectsUrl: https://github.com/Farewellznm
  rss: yes
  show_updated: yes
  showAllPostsOnHomePage: no
  showProjectsList: yes
  social:
    - link: https://github.com/Farewellznm
      name: github
    - link: huishengliu06@gmail.com
      name: email
  tagsOverview: no
  enableEmoji: True
  
  
  
