---
title: "今晚，我什么也没做"
author: "LHS"
date: "2014-06-09"
category: 随笔
tags: 
- 随笔
output: html_document
---

>今晚，我什么也没做


从考场回来，鞋子也破了，褪去留下了夏天汗湿味的带有麻点的衣服，多少个日子都为了一个单纯的目标留下了血汗，如今我赤膊着，在寝室里走来走去。

忽然，晚上就到来了，我自己一个人扛着书去卖，手指已被篮子的棱角给划出血来，却兴奋沉重的忘怀一切。仿佛还是日常一样下午必去西门赞助自助餐一样，我匆匆地去复又回来。可是报歉，我什么也没做。

七点十五分，便上了教室，带了笔，带了赎罪性质的小说《罪与罚》，砖头一般。看了目录，突的没有了兴趣，又去换了《白鹿原》，也看不进。教室里纸屑风飞，书也淡然无存，旁边边桌子上烂泥似的吃罢的西瓜，江西移动发的充50送500的优惠电话卡，红色的袋子，一麻袋一麻袋将换去轻飘飘纸币的书被拉来拉去。可是，我什么也没做。

发春没吃晚饭便来了，恰如其他人一般。班上热闹极了尽管平时更热闹，有人大喊大叫，有人装疯卖萌。排个大约只需几十分钟的档案袋就仿佛到了深夜，因为有人把封条撕了，有人顺序又分不清了，我只有等，因为我什么也没做。

我突然感觉一年下来，到如今，什么都空了，又回到了起初，考完了没有感觉否定自我知识的应试教育考试，倘若能为人所值得，亦也没有遗憾的了，很多同学因为纯粹的目的也没法联系了，因为我什么也没做，只是静静地。

我什么也没做，只是饶了学校一圈，在新教学楼碰见了正在给高三同学签名的陈联湧校长说电话号码在哪儿哪儿有，还有围着一圈对着某个小女生说你是最美的同班男生，多年之后，每每回顾岁月是，这必将是她最美好温情的回忆吧。

我去了停车场，去年天天跑步的地方，没走完一圈便兴趣索然了，便从前门出去走到西门巷口，疲惫之至；我无法停止对未来的追问。

回到寝室，李明斌女朋友在热闹的玩手机，袁超发在刷屏，方园明在弄脚指甲打算去通宵，巫慧在收旧课本，他们在拍照。我什么也没有做。

然后就和袁朝发又出去，他吃粉干和啤酒去了，而我喝了一瓶啤酒。聊聊天，不知不觉就碰到了扫兴的学校保安哥，什么兴趣也没了。就回来了，什么也没做。  

其实，我一直在和曾鉴彬聊QQ的，仿佛时间就如此过去了。但是不然，合上手机便迷糊了，迷糊着说要熬夜看完《钦差大臣》的，可是却睡死了，的的确确的什么也没做。