---
title: "少无所依"
author: "LHS"
date: "2016-02-01"
category: 随笔
tags: 
- 随笔
output: html_document
---
> 记忆是梦幻的，逼着我们一次又一次做梦，似乎我们能因此改变一些东西。


>1

在我初中毕业的时候，我们班有个同学对我说：“我很想接近你，但是又惧怕你，希望你以后能实现自己的梦想。”

俗话说，大象也有大象的记忆，我记住了这些事情，尤其是前半句话是那么的深刻。细细想来他那时这么说的言下之意莫过于：这是个莫名奇怪的家伙，性情乖戾，令人不可亲近。

我很久以前就是个沉默的家伙，也不妄加评论别人，不在公众面前大声说话，这使得我知道认识一些社会上的青年，他们对我很友好，我们经常在河滩上昼夜未眠，看着混浊却波光粼粼的静流，生起的篝火，把雾气驱散，令人异常兴奋。他们给我们讲情色笑话，讲女鬼，讲2003年某天某日大桥下被蚂蚁吃光的女婴。

“你是昨天讲故事的人吗？”我扒开火，把一根红薯扔进去。

“不是。”边上的人说。然而他却讲起了之前我听过的故事。

>2

下面是一些零零碎碎的记忆。

我走上街去买小霸王的游戏卡，问完一家后，打算货比三家，老板对我说：

“不用比了，街上卖这个的都是我亲戚。”

于是我和寝室的老幺在中考前狠玩游戏到天亮。

我打算乘车下赣县去见见城市人，车票八元，掏掏兜，四块八毛钱，算了吧。

我有两尾小金鱼养在放在窗户上的杯子里，屋子里照样是不收拾的，堆满了地的课本和杂书。早上起来，给金鱼们打完招呼，喂了小零食之后就用塑料袋提着书上自习去了。先早操，然后早自习；自习之后也不吃早饭，感觉冷便跑出去闲逛。有时碰到同路回家的班主任，久而久之，他竟然在全班表扬起我这种好好锻炼的习惯了。我依旧独来独往。

我和要好的同学爬上狮子山看圆圆的月亮， 

找我们学校在哪儿，我们的邮政局在哪呢，数学老师家在哪呢。我们一起星期天去上晚自习，在黑板上涂鸦；一起爬围墙；一起偷堆在操场上的木板来做堆书的架子；一起去遛狗；一起在雷雨后在走廊上踢水玩；在火烧云的傍晚写关于它的作文；一起见证了学校最后一排老房子的推到；我们希望得了肺炎的同学快好起来。

>3

我还认识另外一些人，晚自习下完一起回家的两个同班女同学（事实上，我连她们叫什么都忘记了），其中一个用私藏的一元五角钱买了三个雪饼，一人一个；还有同寝室光着膀子一起出去淋雨疯玩的室友；寝室的人在一天早上起来发现所有人的被子都湿了，最后发现了前夜里每个人都以冷为借口不愿意去拔而烧了一夜的热的快；我们一伙人“威胁”着宿舍里的老幺去买三国方便面；我和男同桌在桌底下互相掰手，“秋波暗送”，被语文老师罚拉手一节课。回忆里我的话说的最多。

我记得有时每次回家都是很晚很晚，若是下了雨，就得到十点半以后才能回去。南方夏天的雷雨来的狂涌，那个夏天星期六的晚上正是这种天气，我和一个男同学加上她们俩一块回家。到了最后走的只剩下我和另外一个同行的女同学了，到了她家不远处，雨又哗啦啦大起来了，她叫我先去她家门口躲雨。沿着她家门口唯一一盏灯看去，雨斜斜地穿过诊所，荷塘的水面，等我放眼看去时，已经到了她家门口。门口边上有个小水沟，便顺手把雨伞搁在水沟上，她家门口抬头看去是一片菜地，里面种了葱和卷心菜。待雨小了一些，蛙便放开肺（不清楚有没有肺）叫了起来；莲叶似乎也直了直身子。

“我走了啊。”

“雨还在下，”她拍了拍衣服上的水珠，又说“要不再等会，雨或许就停了呢”，我不理她，挥一挥手。

她没再说什么，毕竟已经很晚了。

她把沿途所有灯都开了。

不久，我的小金鱼饿死了，发现的时候已经发臭了。

我开始好好学习了；我沉默寡言，一度不和同龄人说话。

后来，我曾很多次梦见我踢石子，石子没有发声；我想大声呼唤，可是叫不出声音来。

中考完，我去班主任家喝烧酒去了。

>4

前几天我又踏上回家的路了，灰尘布满的客车，车票半年半年的涨，现在已经十六了，车上唯恐每个人都做不到位子，在车站就已经挑乘客了：

“南塘的来，不要樟溪的。”

家里还是没变，马路没变，平江没变。狮子山前有了大楼，为我开灯的同学家附近的荷塘填平了，建了大楼，

学校也建起了厚厚的围墙，上面插满了玻璃。卖家电的老板的亲戚又开满了一条街。老市场还在用。每个小孩子都有了大大的手机。

回到家的晚上， 我在梦里，梦到了小时候抓螃蟹的河，堆满了修路的大石头，我把它们都搬开，没找到一只螃蟹；我还淋了很多很多雨，又被一个女的大骂了一顿之后，然后冲着我冷笑。

然后我醒了。

