---
title: "从苦楝树谈起"
author: "LHS"
date: "2021-09-02"
category: 随笔
tags: 
- 随笔
output: html_document
---

>风掠过苦楝树的叶子，沙沙作响，像恋人的手帕；你对着苦楝树喊它的名字，它沉默不语，到了秋天，只会落下苦楝子，千千万万遍。可是内心的苦楝子呢，像是生活中一剂失意的药……  2021/09/02

西农南校高大笔直的苦楝树，想必大家都不陌生。春末时分，早上八点左右你匆忙经过苦楝广场时，若仰起头来，和风吹拂，花枝摇曳，像恋人的手帕似的；到了深秋雨季的时候，天总是阴沉沉的，你怀着低落的心情走过，所有的苦楝子都似乎变得苦涩，那坠落的声音和雨的阒静交相辉映。

我从苦楝树谈起是为了谈谈对我们生活的一点认识。我已经来南校一年久了，平时一有空就去广场附近坐着消食，或者想一些其他东西，特别是这个夏天，一有空就去。现在我们有空来欣赏苦楝树，刚来学校的一定会想苦楝树可以做木柴，果实、叶子和树皮都可以入药，刚学完植物学的你，一定会说苦楝是属于楝科落叶乔木植物，它的叶子是奇数羽状复叶；你再仔细想发现前者是实用的态度，后者是科学的态度，我们知道了苦楝的具体的理化成分也就明白了它的用途所在，所以说实用和科学是有因果联系的。

大学所教授的知识以及科学工作者研究的东西往往是科学和实用的，譬如教授的麦子增产理论以及具体的农业机械化实现，固然科学实用的态度并不可少；然而这些远远不够，我们还需要美的态度，而审美也是如今大学生最缺少的态度之一。为什么这么说呢？举个实际的例子，临近毕业了的同学或许都在忙于择业升学，更不急的低年级的同学们正在好好积累学分，积极做实践活动，季节更替，我们从苦楝树下经过时，谁会感慨一颗苦楝树的喜乐悲哀，谁会在意它的美呢？

怎么才算美呢？美是羊羹的味道，美是姣好面容的女子，固美不一而足。一方面，事物经过个人的直觉而变成形相，形相产生美感，美感体验是人与物一同作用的，亦是说，对一件事物或人的美丑，一半是其自身决定的，另一半是你我主观认为的。物无美之前提则直觉无作用，直觉无物可审则美感无由而出，“东施效颦”说的就是前者；若没有泰山，《诗经》也不会有“泰山岩岩，鲁邦所詹”的佳句；另一方面，美感的产生反应人情趣的差异；每个人对待相同事物的直觉是不一样的，“生活不缺美，缺的是发现美的眼睛”，美丑的产生往往产生于不同人的观察。

直觉与形相产生美感，“直觉是脱离意志抽象的思考，形相是直觉见到的孤立绝缘的物体”，怎么理解这句话呢？我们不像一开始那样把苦楝树联想到各种药用，也不像学过植物科学一样细究它的根茎叶花果实，我们转而把这株苦楝树当作整体来看，把它作为一个世界，去感受它的悲伤喜乐。绝缘的看待苦楝树，没有切身的利益所在，也不去破坏它的整体和谐。

前几天，我去北校，恰逢烟雨朦朦，正在伞下欣赏游泳池附近的一颗垂柳，我那时什么烦心事都不想，睁大眼睛，柳树和雨帘整个映入眼帘，垂柔的枝条，像母亲的头发一样，清新自然，仿佛回到家乡似的，让人亲切，让人心情开朗起来。

“距离产生美”，距离太远，观察事物朦胧，只能客观的说几句话；距离太近，涉及到自己的各个方面的利益，也就无暇审美；距离适中，才可慢慢把玩，赏心悦目。小时候经常认为别人家的菜就是比自己母亲做的好吃的多，说的就是这个道理；上大学了，喜欢上一个女孩了，发现追求的时候烦心的事情一件又一件，大概是患得患失，倘若把人家当成普通盆友，却能真正发现人家的可爱之处；“当局者迷，旁观者清”也是距离问题，不用割麦子的游客有心情享受麦子的波浪，割着麦子的老农反会说，有什么好看的，俺农民也只挣着几个钱，累的死，因而，自己手头的事情，普通人很难不会陷于其中。

这还要提及一个误区，很多人对美感存在错误的认知。实用性往往令人产生错误的美感，譬如大学女生寝室发生的事：女生之间一个人说哪个女生不好，周围的人很容易实用的也以为那个女生不好；譬如你想看一本书，别人给你推荐马尔克斯，你一定也会认为那本书一定不赖吧，这些判断到底还是持了实用态度，都不是真正的美感体验，真正的美感体验是自己通过直觉去感受的。如果有了这个前提，就不难解释“爱屋及乌”的道理了，譬如，你喜欢一座城市，并不是因为它有你不得不爱的地方，更多的时候，有种情况是，你持实用的态度将你爱的那个她与这座城市联系起来了，其实这算不上美感，一但你和她的联系解除，那个城市也必会成为伤心之地了，所以真正的美感体验是亲身恭行的。

很久之前，有个人在爬苦楝树，到了三四米的高度，我正好路过，对他说，“你爬树难免害了你和树的，”他瞥了我一眼，没说任何一句话。其实我当时是持了实用的态度去评价人家，事后我想解释这件事的理由，或许他在练习爬树呢，或许他对这棵树有情感（审美中的移情作用），他在爬他的生命之树呢，这么一想，后悔当初为什么不保留评价呢。这告诉我不能持实用的先验的态度待人待事，不过这的确很难，不然人与人之间定会天下太平，也告诉我自己对他人的评价有一半可能是不正确的，这让我学会像盖茨比一样谨言慎评。

我曾梦见诗人的作品被要求上进的妻子扔在了下水道，我曾见过滑溜溜忙于社交的大忙人，这的或许反映了今下的现实，就把学校的事情拿来举例子吧。我学习的是农业，可是触目之下，我看见的都是疲于应付专业考试而学习的人，为了深造而拼命学习英语的人，当然我曾经也是其中一员，我想这或许就是距离太近，牵涉自身利益太多，反而看不见农业学科的美吧。不在乎这些条条框框的人，反而活得自然些。

当下，自然科学和社会科学越来越紧密联系，往往“荷叶藕，满塘转”，学科之间牵一发动全身，学习农业理论课的同时，我们往往忘了美学、文学、社会学、地理、数学的学习，只学农学不学其他，闭门造车，分数再高，也学不会农学；重点是我所处的环境往往缺乏美感培养等，我们太忙，甚至没有时间好好自学下所谓的课外书。

一位辅导员终于有时间看本书了，面对繁多种类的书，说道：“这些我都不爱看”；大学生获取信息的途径主要是刷手机，阅读量少之又少；我记得我借给一位同学一本《瓦尔登湖》，三个月之后还给我时，一尘不染。从审美角度说，在心灵闲余时，读书只不过是为了心灵的归宿，我们大可不必计较数量，我们读的是各门类的书，感受书中所带来的美感体验，事后，丰富自己的思维方式和性格。读书是大学生美感体验的一种重要方式，这样下来，从这方面来说，当下总体大学生美感体验水平是及其低下的。从实用角度说，我见过很多忙于实事的人，读书对于他们来说是一项繁重的事情。他们瞎跑乱逛，疲于奔命，忙于应付。若忙于生计发展我并不反对，但是没有思考的瞎跑玩乐就没有意义了。而这些思考往往是专业知识不能解决的，必先多积攒眼界，才能更好实践，所以广泛读书很重要。

瞎扯到很远，回到美上，美到底是没有任何实际用处，这样看来，你我彼此之间其实并无多大影响；但是，美感确是精神世界不可缺少的。百年之后，出将入相的权贵或许已被人遗忘，临渔问樵的隐士反而因他的精神思想为人们所熟记。朱光潜老先生说的好，我们应该像“思想家和艺术家”一样努力的散播几点星光！

这篇文章是读朱光潜《谈美》《谈美书简》时所记录的笔记整理出来的，借鉴模仿，写成一篇感想谈谈对书中和生活中的一点认识；八月的尾巴，秋雨歇去，暖阳驱散寒意，精神抖擞，走在苦楝广场的树荫下，我们的知了歌手在夏天还没唱个尽兴，现在正在斑驳树丫上继续他伟大的事业，愿我们以后的心情也向今天一样暖洋洋！ 2017-08-25
