---
title: "NGS分子生物学知识：细胞系统"
author: "LHS"
date: "2021-05-05"
category: 科普
tags: 
- 科普
output: html_document
draft:  true
---
这是一系列简要分子生物学[^1]知识总结：

# 细胞与微环境

细胞是一个体积小于50um的精巧系统，体现在其具有复杂的内部组成，能够在DNA指导下进行新陈代谢，维持内部与周边微环境之间的互动；同时细胞可以发生分化以行使特定功能。下面是一个具体的例子：

>成熟B细胞受到癌细胞抗原刺激后分化而成的浆细胞可以分泌抗体，进而杀死癌细胞

这句话表明了环境对细胞的影响，`癌细胞抗原对成熟B细胞影响`；细胞分化为浆细胞获得分泌抗体的能力，此时受其内部DNA等的调控；浆细胞通过分泌抗体对环境的负反馈，`杀死癌细胞`。

# 细胞组成

细胞由细胞核、细胞膜、细胞质、溶酶体和过氧化氢酶体、核糖体、内质网、高尔基体、细胞骨架、线粒体、叶绿体组成；

1. `细胞核`储存有DNA，处于细胞中心，由核膜、核孔、骨架组成。DNA缠绕在组蛋白上高度压缩存储在有限的核空间上，因而DNA在核内的如何高效的组装是一个有趣的问题；DNA的复制和转录都在核内进行，后者RNA的跨膜运输需要通过核孔；同时`核孔`还可以进行蛋白质的跨膜运输，例如，JAK-STAT信号通路中的信号转导及转录激活蛋白（STAT）易位到细胞核中影响下游基因的表达。

2. `细胞膜`可以从环境接受信号，通过模上的受体，级联反应放大信号，引起细胞状态的变化.

3. `细胞质`包括细胞器和细胞液，糖酵解、信号转导等大多数都发生在细胞液中；值得一提的是细胞液中Ca<sup>2+</sup>浓度很低，在特定条件下，信使Ca<sup>2+</sup>可以通过离子泵进入，引发下游信号反应，导致基因表达水平的变化。

4. `溶酶体和过氧化氢酶体`：溶酶体内为酸性环境，可以消化外来物质和细胞内淘汰物质。过氧化氢酶体可以通过过氧化来氧化酚类和醇类物质，如肝细胞用这些反应来对有毒物质降解；过氧化氢酶体的起源目前还不清楚，一种假说是，`内共生`共生生物核基因组完全整合进核基因组中；一种假说是，在古生物时期，氧气对大多数细胞具有毒害作用，这种细胞器可以降低胞内氧浓度，因而过氧化物酶体仍然保留在胞内进行有益的氧化反应。

5. `核糖体`是蛋白质工厂，可以将mRNA翻译成蛋白质。核糖体rRNA在核仁组装，运输到细胞质中游离存在，或依附在内质网上。由于rRNA占细胞RNA总量85~90%，所以在NGS研究中，rRNA作为不感兴趣的部分在测序之前会被去除，以免结果中存在大量的rRNA序列。

6. `内质网`分为粗面和滑面内质网。粗面内质网负责蛋白质加工：分泌蛋白，如胰岛素等，通过tag标签进入内质网中进一步加工；滑面内质网用于细胞膜相关脂类的合成，同时也负责将泵入的Ca<sup>2+</sup>隔离开。

7. `高尔基体`负责蛋白的进一步分选，对蛋白质进行进一步修饰。植物细胞中还可以合成碳水化合物和细胞壁的多糖等。

8. `细胞骨架`主要由微丝、微管中间纤维组成。微丝、微管由肌动蛋白和微管蛋白组成，将mRNA+核糖体组成的翻译机器运输到特定部位；微管也会在有丝分裂中染色体分配过程中行驶重要作用。

9. `线粒体`通过三羧酸循环和氧化磷酸化产生能量（ATP）。目前认为线粒体起源于内共生的古老α-变形杆菌,人类线粒体DNA中共有37编码基因，其中22个编码tRNA，2个编码rRNA，13个编码线粒体蛋白质。由于多拷贝，细胞中含有大量的线粒体，在测序中会有相当一部分是线粒体DNA，甚至大部分是。麻雀虽小，但是其具有复制转录翻译全套的蛋白因子，在RNAseq中有相当一部分是线粒体产物。同时，在多拷贝的线粒体中，由于突变的存在，会出现异质性的线粒体DNA。一般线粒体DNA突变率大于核DNA，原因在于高能电子在传递时，会产生活性氧，进而引起线粒体突变；更糟糕的是线粒体DNA修复能力很差。线粒体异质性的增加和AD、PD以及心脏病有关，同时也是肌肉方面的疾病的病因。

10. `叶绿体`是植物和藻类用于通过捕获光能产生ATP来固定CO2转化为糖类，包括光反应和暗反应。叶绿体被认为由内共生的蓝藻进化而来，其他的特性和线粒体类似。

# 细胞的系统生物学研究

细胞通过DNA的调控具有自主调节能力，通过各组分的相互协作来维持细胞系统的稳定性，这种细胞系统的平衡具有很高的复杂度。不同于单个组分的研究，系统生物学是用来研究细胞不同组分之间的相互作用的学科，细胞的功能表现在细胞系统中遗传物质流的进行，各种流形成网络。

系统生物学的一个目标是绘制遗传网络，其具有非生物网络，`无尺度网络`[^2]（互联网、社交网、交通网）的一些特点。第一个是，模块化。多个基因和蛋白质共同起作用；另外一个是，具有枢纽（hub）节点，表现在高度连结的基因或蛋白。

最后NGS，基因组学、转录组学、蛋白质组学与代谢组学已经用于对系统生物学进行进一步研究。

# Ref：

[^1]:（美）王忻琨 著;陈浩峰 译. 新一代测序数据分析[M]. 北京：科学出版社, 2018

[^2]:[无尺度网络](https://zh.wikipedia.org/wiki/%E6%97%A0%E5%B0%BA%E5%BA%A6%E7%BD%91%E7%BB%9C)
























